### ISSUE TITLE
Option<T>?

### ISSUE THREAD

**Issue by SoniEx2** [droundy/arrayref#13]
Would it be possible to have an array_ref variant with Option<T>?

**Comment by droundy** [comment]
I don't understand what you're looking for. Can you give a code example?

**Comment by SoniEx2** [comment]
```rust
fn from_slice(s: &'a [u8]) -> Option<Numeric<'a>> {
  Self::new(try_array_ref![s, 0, 3]?)
}
```

As opposed to what I'm currently using:

```rust
    pub fn new_from_slice(cmd: &'a [u8]) -> Option<Numeric<'a>> {
        if cmd.len() == 3 {
            // TODO switch to TryFrom/TryInto once those are stable. (rust-lang/rust#33417)
            Self::new(array_ref![cmd, 0, 3])
        } else {
            None
        }
    }
```

**Comment by SoniEx2** [comment]
And yes, I know array_ref takes a "subslice" not an array ref to the whole thing. So I'd still need that `if`, I guess.

Meh. Oh well.

**Comment by droundy** [comment]
I'm thinking that you're wanting a version of `array_ref` which returns `None` rather than panicking if the slice is too small? But that you've now realized that you want to have confirm that `try_array_ref` will consume the entire slice, so just checking that the slice is big enough isn't helpful to? If so, my leaning is to close this as a won't fix kind of situation.

I can see an appeal to a non-panicking version of `array_ref!`, but it also seems somewhat unrustish.  In rust, failure to index correctly is a panic situation.  For array reference input (rather than slices), `array_refs!` is a superior option which will never panic.

**Comment by SoniEx2** [comment]
And then there's .get() on slices which returns an Option.

**Comment by burdges** [comment]
It's fairly trivial to do this yourself in a wrapper on `array_refs!` because `array_ref!` does minimal arithmetic, unlike `array_refs!`.
